name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run the custom AWS IoT action
        uses: ./
        with:
          thing-name: "my-test-thing"
        env:
          AWS_DEFAULT_REGION: "us-west-2"
