name: "Setup AWS IoT Action"
description: "Sets up AWS IoT Thing, Role, Policy, Keys, etc., and handles cleanup automatically"
inputs:
  thing-name:
    required: true
    description: "IoT Thing Name"

  iam-role-name:
    required: true
    description: "Name of IAM role"

  iam-policy-name:
    required: true
    description: "Name of IAM policy that gets attached to IAM role"

  iam-policy-string:
    required: true
    description: "IAM permissions policy"

runs:
  using: "node20"
  main: "dist/setup/index.js"
  post: "dist/cleanup/index.js"
